### ISSUE TITLE
Unable to set value of a text field

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/deephaven-plugins#447] opened 2024-04-29 19:42 UTC
```python
from deephaven import ui
from deephaven.ui import use_state

@ui.component
def test():
    text, set_text  = use_state("abc")
    return [
        ui.text_field(value=text, on_change=set_text ),
        ui.action_button("Reset", on_press=lambda: set_text("")),
        ui.text(text),
    ]

t = test()
```

I have a reset button that is supposed to clear the field but it doesn't work. Clicking reset does change the state of text, but the value of the field isn't updated.

**Comment by mofojed** [comment] 2024-05-28 13:35
Duplicate of #372

**Closed by mofojed** 2024-05-28 13:35 UTC
Labels: bug
