### ISSUE TITLE
ui.flex is missing many props now

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#902] opened 2024-09-23 13:28 UTC
**Description**

As a result of ui.flex no longer just accepting `**props` after PR #810 , it's now missing some props: https://react-spectrum.adobe.com/react-spectrum/Flex.html#props
Add the missing props and document.

**Steps to reproduce**
1. Add a flex with a height set:
```python
from deephaven import ui

f = ui.flex("Hello", height="size-3000")
```

**Expected results**
1. Flex element should appear

**Actual results**
1. An error is thrown:
```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'TypeError'>
Value: flex() got an unexpected keyword argument 'height'
Line: 3
```

**Versions**
Engine Version: 0.36.1
Web UI Version: 0.90.0
Java Version: 11.0.24
Barrage Version: 0.6.0
Browser Name: Chrome 128
OS Name: Linux
@deephaven/js-plugin-plotly-express: 0.11.2
@deephaven/js-plugin-ui: 0.21.0

**Comment by mofojed** [comment] 2024-09-23 13:33
@ethanalvizo 's already fixing this as part of his flex docs PR: #785

**Comment by dsmmcken** [comment] 2024-09-23 13:49
Duplicate of #824

**Closed by dsmmcken** 2024-09-23 13:49 UTC
Labels: bug
